### ISSUE TITLE
M1: Error when building from source

### ISSUE THREAD

**Issue by coetry** [drcode/zek#3]
After cloning the repo and running `zig build` in the `src` directory, I ran into the following error when attempting to build on Apple Silicon:

```
./zek.zig:1607:73: error: no member named 'mode' in struct 'std.fs.file.OpenFlags'
        var tty: std.fs.File = try std.fs.cwd().openFile("/dev/tty", .{ .mode = std.fs.File.OpenMode.read_write });
```

**Zig Version: 0.9.0**

**Comment by drcode** [comment]
Thanks, I think this is because Zig is a moving target and we are too far ahead on zig, try the previous commit, which will likely work in zig 0.9.0
https://github.com/drcode/zek/commit/4c7db3f164fe12ee320404f664dd39db2c01e72a

Or try zig 0.10.0 instead.

Sorry, can't investigate for a couple of days, will investigate when I can.

**Comment by drcode** [comment]
Hi @coetry, so I verified that everything works fine in zig 0.10.0, I updated the README.md to indicate 0.10.0 is required. I probably should have waited until 0.10.0 was officially released before switching over, but somebody already did the porting work and I couldn't resist merging in their pull request LOL.
